# Generated by Django 5.0.6 on 2024-06-11 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemsupplier",
            name="inventory_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_suppliers",
                to="stores.inventoryitem",
            ),
        ),
        migrations.AlterField(
            model_name="itemsupplier",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_items",
                to="stores.supplier",
            ),
        ),
    ]
